# AI小売システム設定ファイル
database:
  host: "localhost"
  port: 5432
  name: "retail_ai_db"
  user: "retail_user"
  password: "your_password"

api_keys:
  weather_api: "your_weather_api_key"
  economic_data_api: "your_economic_api_key"

model_settings:
  demand_forecasting:
    horizon_days: 30
    retrain_frequency: 7  # days
    min_accuracy_threshold: 0.85
  
  inventory_optimization:
    service_level: 0.95
    review_period: 7  # days
    
  price_optimization:
    max_price_change_percent: 20
    min_margin_percent: 15
    
  recommendation:
    num_recommendations: 10
    min_rating: 3.0

alerts:
  email_notifications: true
  slack_webhook: "your_slack_webhook_url"
  
monitoring:
  log_level: "INFO"
  metrics_retention_days: 90
